"""LangGraph agent state definition.

This module defines the state structure for the ByteBuddhi LangGraph agent.
The state tracks conversation context, retrieved code, and agent decisions.
"""

from typing import Any, Dict, List, Optional, TypedDict

from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """State for the ByteBuddhi coding agent.
    
    This TypedDict defines all state variables that are passed between
    agent nodes during execution. The state accumulates information
    as the agent processes the user's request.
    
    Attributes:
        messages: Conversation history (user and assistant messages)
        user_query: Current user query/request
        intent: Classified intent (e.g., 'code_generation', 'explanation', 'debug')
        project_id: ID of the project being worked on
        retrieved_context: Code chunks retrieved from vector store
        generated_code: Code generated by the agent
        explanation: Explanation or response text
        error: Error message if something went wrong
        metadata: Additional metadata for the interaction
    """
    
    # Conversation history
    messages: List[BaseMessage]
    
    # Current request
    user_query: str
    
    # Intent classification
    intent: Optional[str]
    
    # Project context
    project_id: Optional[str]
    
    # Retrieved code context
    retrieved_context: List[Dict[str, Any]]
    
    # Generated outputs
    generated_code: Optional[str]
    explanation: Optional[str]
    
    # Error handling
    error: Optional[str]
    
    # Additional metadata
    metadata: Dict[str, Any]


class IntentType:
    """Intent types for agent classification.
    
    These constants define the different types of user intents
    the agent can handle.
    """
    
    CODE_GENERATION = "code_generation"
    CODE_EXPLANATION = "code_explanation"
    CODE_DEBUG = "code_debug"
    CODE_REFACTOR = "code_refactor"
    QUESTION_ANSWER = "question_answer"
    GENERAL_CHAT = "general_chat"
    
    @classmethod
    def all_intents(cls) -> List[str]:
        """Get all available intent types.
        
        Returns:
            List[str]: List of all intent type strings
        """
        return [
            cls.CODE_GENERATION,
            cls.CODE_EXPLANATION,
            cls.CODE_DEBUG,
            cls.CODE_REFACTOR,
            cls.QUESTION_ANSWER,
            cls.GENERAL_CHAT,
        ]
