"""Write the desktop TypeScript contracts from the backend models.

The FastAPI models and the execution-event enum are the source of truth.
This script does not start a server and does not use the network.
"""

from __future__ import annotations

import json
from pathlib import Path

from app.application.runtime.events import ALLOWED_EXECUTION_PAYLOAD_KEYS, ExecutionEventType
from app.interfaces.api.schemas.chat_schema import ConversationResponse, MessageResponse
from app.interfaces.api.schemas.model_schema import ModelCatalogResponse
from app.interfaces.api.schemas.project_schema import ProjectResponse
from app.interfaces.api.schemas.run_schema import (
    CancelRunResponse,
    RunCreateResponse,
    RunEvent,
    RunEventPage,
    RunResponse,
)

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "desktop" / "renderer" / "src" / "generated"
REQUIRED = (
    "run_queued",
    "run_started",
    "assistant_delta",
    "tool_started",
    "tool_completed",
    "message_created",
    "run_completed",
    "run_failed",
    "run_cancel_requested",
    "run_cancelled",
    "run_interrupted",
)


def main() -> None:
    event_types = [item.value for item in ExecutionEventType]
    missing = [name for name in REQUIRED if name not in event_types]
    if missing:
        raise SystemExit(f"Backend event enum is missing {missing}")
    keys = sorted(ALLOWED_EXECUTION_PAYLOAD_KEYS)
    schemas = {
        "RunEvent": RunEvent.model_json_schema(),
        "RunEventPage": RunEventPage.model_json_schema(),
        "RunCreateResponse": RunCreateResponse.model_json_schema(),
        "RunResponse": RunResponse.model_json_schema(),
        "CancelRunResponse": CancelRunResponse.model_json_schema(),
        "ProjectResponse": ProjectResponse.model_json_schema(),
        "ConversationResponse": ConversationResponse.model_json_schema(),
        "MessageResponse": MessageResponse.model_json_schema(),
        "ModelCatalogResponse": ModelCatalogResponse.model_json_schema(),
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "schemas.json").write_text(json.dumps(schemas, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (OUT_DIR / "contracts.ts").write_text(_typescript(event_types, keys), encoding="utf-8")


def _typescript(event_types: list[str], keys: list[str]) -> str:
    event_union = "\n".join(f'  | "{name}"' for name in event_types)
    key_union = "\n".join(f'  | "{name}"' for name in keys)
    event_list = ",\n".join(f'  "{name}"' for name in event_types)
    key_list = ",\n".join(f'  "{name}"' for name in keys)
    return f"""/* Generated by scripts/export_desktop_contracts.py. Do not edit. */
export const SCHEMA_VERSION = 1

export const RUN_EVENT_TYPES = [
{event_list},
] as const

export const ALLOWED_EVENT_DATA_KEYS = [
{key_list},
] as const

export type RunEventType =
{event_union}

export type EventDataKey =
{key_union}

export type EventDataValue = string | number | boolean | null

export type RunEvent = {{
  event_id: string
  run_id: string
  sequence: number
  type: RunEventType
  schema_version: number
  created_at: string
  data: Partial<Record<EventDataKey, EventDataValue>>
}}

export type RunEventPage = {{
  events: RunEvent[]
  next_sequence: number
  has_more: boolean
}}
"""


if __name__ == "__main__":
    main()
